### ISSUE TITLE
Using Protobufs

### ISSUE THREAD

**Issue by Mikerah** [Whiteblock/hobbits#22]
I was going to start implementing this in TypeScript and thought this could be done easily using protocol buffers.

Are there any major issues to using Protobufs to implement hobbits?

**Comment by zscole** [comment]
I wouldn't anticipate any issues. Protobufs is just a serialization method, so you should be able to use on top of Hobbits no problem. Let us know how it works out though!

**Comment by Mikerah** [comment]
thanks
