### ISSUE TITLE
Clarification for `header` and `body` fields in `Request` and `Response`

### ISSUE THREAD

**Issue by Mikerah** [Whiteblock/hobbits#28]
From looking at the example code and example wire messages, it seems like the `header` and `body` fields for both `Request` and `Response` should be some unsigned integer instead of `bytes` and perhaps renamed to `headerLength` and `bodyLength` or instead add these extra attributes. 

Currently, `header` and `body` seem to indicate the length, i.e., number of bytes it takes up in the payload instead of the actual `header` and `body` respectively.

**Comment by atoulme** [comment]
Are you referring to the BNF grammar? If yes, this should be fixed now:
https://github.com/Whiteblock/hobbits/blob/master/Ethereum-Wire-Protocol-0.2.EBNF

**Comment by Mikerah** [comment]
Closing since resolved and updated in EWP 0.2.
