### ISSUE TITLE
Adding a `has_body` field to `Response` message

### ISSUE THREAD

**Issue by Mikerah** [Whiteblock/hobbits#29]
I noticed that in a lot of the demo implementations, when defining a `Response` message, include a `has_body` to indicate whether the `Response` message contains a body. However, not all implementations do this.

Is this more of an implementation detail that is left up to implementers or should a `has_body` attribute be added to the `Response` message?

**Comment by n8wb** [comment]
It really depends on whether you would like a special condition to handle a non-existent body versus an empty body.  The non-existent body case must be handled by the demo implementations, but the empty body does not, at least as of right now. We can add support for the empty body as a requirement if there is a need for it. However, as of right now, it doesn't appear as though there will be a situation where the client will need to distinguish between the two.

**Comment by zscole** [comment]
I think this has been addressed in @atoulme's latest PR.

**Comment by atoulme** [comment]
No more `Response` messages...

**Comment by Mikerah** [comment]
Due to the update hobbits spec, this issue is no longer relevant. Closing.
