### ISSUE TITLE
Add URI scheme for hobbits peers 

### ISSUE THREAD

**Issue by atoulme** [Whiteblock/hobbits#30]
For hobbits peers, I suggest we use the following syntax:

Insecure TCP `hob+tcp://10.0.0.1:9000`
Insecure UDP `hob+udp://10.0.0.1:9000`

TLS TCP `hobs+tcp://10.0.0.1:9000`
TLS UDP `hobs+udp://10.0.0.1:9000`

**Comment by zscole** [comment]
Yup, makes sense to me.
