### ISSUE TITLE
Add body max size

### ISSUE THREAD

**Issue by atoulme** [Whiteblock/hobbits#33]
Secure Scuttlebutt uses 4096 bytes maximum size for message bodies. We should do the same here.

**Comment by n8wb** [comment]
I don't believe that a limit should be imposed in the protocol. However, if we add it as a feature, it should at least be optional, and the amount defined by the user.  Such as how HTTP is often implemented, technically having no limit on its body, but often times capped at 2GB. My reasoning is simply that there may be unforeseen use cases and that we should keep this level of the protocol as simple as possible. This gives the implementer/user more freedom, and prevents the potential issue of users having to work around the protocol.

**Comment by zscole** [comment]
@atoulme, I agree with @n8wb on this one. Is there a particular reason a max size should be implemented? Is this to prevent overflow?

**Comment by atoulme** [comment]
OK let's keep this out for now.
